"""nftables guidance and optional renderer. Never opens PostgreSQL or the API."""

from __future__ import annotations

NFT_TEMPLATE = """#!/usr/sbin/nft -f
# Generated by MailGate. Review before applying.
# This file does not expose PostgreSQL (5432) or the MailGate API (8000).

flush ruleset

table inet mailgate {
    chain input {
        type filter hook input priority 0; policy drop;

        ct state established,related accept
        iif lo accept

        ip protocol icmp accept
        ip6 nexthdr ipv6-icmp accept

        tcp dport {ssh_port} accept
        tcp dport 25 accept
        tcp dport 80 accept
        tcp dport 443 accept
        # Optional submission — disabled by default
        # tcp dport 587 accept
        # tcp dport 465 accept
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
    }

    chain output {
        type filter hook output priority 0; policy accept;
    }
}
"""


def render_nftables(ssh_port: int = 22, allow_ssh: bool = True) -> str:
    port = ssh_port if allow_ssh else 0
    body = NFT_TEMPLATE.replace("{ssh_port}", str(port) if allow_ssh else "22")
    if not allow_ssh:
        body = body.replace("        tcp dport 22 accept\n", "")
        body = body.replace(f"        tcp dport {ssh_port} accept\n", "")
    return body


def guidance(local_ip: str | None, ssh_port: int = 22) -> dict:
    target = local_ip or "THIS_MACHINE_LAN_IP"
    return {
        "backend": "nftables",
        "expose": [
            {"port": 25, "proto": "tcp", "service": "SMTP"},
            {"port": 80, "proto": "tcp", "service": "HTTP / ACME"},
            {"port": 443, "proto": "tcp", "service": "HTTPS dashboard"},
            {"port": ssh_port, "proto": "tcp", "service": "SSH (optional/restricted)"},
        ],
        "never_expose": [
            {"port": 5432, "service": "PostgreSQL"},
            {"port": 8000, "service": "MailGate API (localhost only)"},
            {"port": 3000, "service": "Next.js dev server"},
        ],
        "router_forwarding": [
            f"TCP 25 → {target}:25",
            f"TCP 80 → {target}:80",
            f"TCP 443 → {target}:443",
        ],
        "nftables": render_nftables(ssh_port=ssh_port),
        "note": (
            "MailGate can write a suggested nftables ruleset under "
            "/etc/mailgate/nftables.nft. Review it before loading. "
            "The installer will not lock you out of SSH if allow_ssh is enabled."
        ),
    }
