"""Generate Postfix maps and main.cf fragments safely.

User input never enters a shell. Maps are written as files and compiled
with postmap. A working configuration is copied aside before replace,
and restored if `postfix check` fails.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from pathlib import Path

from sqlalchemy.orm import Session

from mailgate.config import load_config, parse_size
from mailgate.paths import POSTFIX_DIR
from mailgate.policy import load_routing_table
from mailgate.validate import postfix_map_safe

MAIN_CF_MARKER_BEGIN = "# BEGIN MAILGATE MANAGED"
MAIN_CF_MARKER_END = "# END MAILGATE MANAGED"
SYSTEM_MAIN_CF = Path("/etc/postfix/main.cf")
BACKUP_MAIN_CF = Path("/etc/postfix/main.cf.mailgate.bak")


class PostfixError(RuntimeError):
    pass


APPLY_HELPER = Path("/usr/lib/mailgate/bin/mailgate-apply-postfix")
QUEUE_HELPER = Path("/usr/lib/mailgate/bin/mailgate-queue")


def _run(cmd: list[str], timeout: int = 30) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=False, capture_output=True, text=True, timeout=timeout)


def _sudo(cmd: list[str], timeout: int = 30) -> subprocess.CompletedProcess:
    if hasattr(os, "geteuid") and os.geteuid() == 0:
        return _run(cmd, timeout=timeout)
    if shutil.which("sudo"):
        return _run(["sudo", "-n", "--", *cmd], timeout=timeout)
    return _run(cmd, timeout=timeout)


def virtual_maps(session: Session) -> tuple[str, str]:
    """Return (virtual_domains file contents, virtual aliases file contents)."""
    domains = load_routing_table(session)
    domain_lines: list[str] = []
    alias_lines: list[str] = []
    alias_lines.append("# Generated by MailGate. Do not edit.")
    domain_lines.append("# Generated by MailGate. Do not edit.")

    for domain in domains:
        if not (domain.enabled and domain.verified):
            continue
        name = postfix_map_safe(domain.name)
        domain_lines.append(f"{name} OK")

        for alias in domain.aliases:
            if not alias.enabled:
                continue
            dests = [postfix_map_safe(d.email.lower()) for d in alias.destinations if d.enabled]
            if not dests:
                continue
            local = postfix_map_safe(alias.local_part)
            left = f"{local}@{name}"
            alias_lines.append(f"{left}\t{','.join(dests)}")

        if domain.catch_all_enabled and domain.catch_all_destination:
            dest = postfix_map_safe(domain.catch_all_destination.lower())
            alias_lines.append(f"@{name}\t{dest}")

    return "\n".join(domain_lines) + "\n", "\n".join(alias_lines) + "\n"


def render_main_cf_snippet() -> str:
    cfg = load_config()
    hostname = cfg.server.hostname
    size = parse_size(cfg.smtp.max_message_size)
    inet_protocols = "all" if cfg.smtp.enable_ipv6 else "ipv4"
    virtual_domains = str(POSTFIX_DIR / "virtual_domains")
    virtual = str(POSTFIX_DIR / "virtual")
    lines = [
        MAIN_CF_MARKER_BEGIN,
        f"myhostname = {hostname}",
        "mydestination = localhost",
        "inet_interfaces = all",
        f"inet_protocols = {inet_protocols}",
        "mynetworks = 127.0.0.0/8 [::1]/128",
        "relay_domains =",
        "local_transport = error:local delivery is disabled",
        f"virtual_alias_domains = hash:{virtual_domains}",
        f"virtual_alias_maps = hash:{virtual}",
        "smtpd_relay_restrictions = permit_mynetworks, reject_unauth_destination",
        "smtpd_recipient_restrictions = permit_mynetworks, reject_unauth_destination, reject_unverified_recipient",
        "smtpd_helo_required = yes",
        "disable_vrfy_command = yes",
        "smtpd_delay_reject = yes",
        f"smtpd_client_connection_rate_limit = {cfg.security.smtp_conn_rate}",
        f"smtpd_client_connection_count_limit = {cfg.security.smtp_conn_count}",
        f"smtpd_recipient_limit = {cfg.security.smtp_recipient_limit}",
        f"message_size_limit = {size}",
        "smtpd_tls_security_level = may",
        "smtp_tls_security_level = may",
        "smtpd_tls_auth_only = yes",
        "smtpd_tls_loglevel = 1",
        "smtp_tls_loglevel = 1",
        "smtpd_tls_received_header = yes",
        "compatibility_level = 3.6",
        MAIN_CF_MARKER_END,
        "",
    ]
    # reject_unverified_recipient can cause false rejects for some forwards.
    # Keep reject_unauth_destination as the open-relay lock; drop unverified.
    lines = [ln for ln in lines if "reject_unverified_recipient" not in ln]
    # Re-add recipient restrictions without unverified
    rebuilt = []
    for ln in lines:
        if ln.startswith("smtpd_recipient_restrictions"):
            rebuilt.append(
                "smtpd_recipient_restrictions = permit_mynetworks, reject_unauth_destination"
            )
        else:
            rebuilt.append(ln)
    return "\n".join(rebuilt)


def write_maps(session: Session) -> None:
    POSTFIX_DIR.mkdir(parents=True, exist_ok=True)
    domains_body, aliases_body = virtual_maps(session)
    domains_path = POSTFIX_DIR / "virtual_domains"
    aliases_path = POSTFIX_DIR / "virtual"
    _atomic_write(domains_path, domains_body)
    _atomic_write(aliases_path, aliases_body)
    # postmap is run by the privileged helper during apply_and_reload.


def _atomic_write(path: Path, content: str, mode: int = 0o640) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name, dir=str(path.parent), text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.chmod(tmp, mode)
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            try:
                os.unlink(tmp)
            except OSError:
                pass


def merge_main_cf(existing: str, snippet: str) -> str:
    begin = existing.find(MAIN_CF_MARKER_BEGIN)
    end = existing.find(MAIN_CF_MARKER_END)
    if begin != -1 and end != -1 and end > begin:
        end = end + len(MAIN_CF_MARKER_END)
        return existing[:begin].rstrip() + "\n\n" + snippet + "\n" + existing[end:].lstrip("\n")
    if existing and not existing.endswith("\n"):
        existing += "\n"
    return existing + "\n" + snippet + "\n"


def apply_main_cf() -> None:
    snippet = render_main_cf_snippet()
    tmp_path = Path("/etc/postfix/main.cf.mailgate.tmp")
    if not SYSTEM_MAIN_CF.exists():
        try:
            _atomic_write(SYSTEM_MAIN_CF, snippet, mode=0o644)
        except PermissionError:
            _atomic_write(tmp_path, snippet, mode=0o644)
        return
    original = SYSTEM_MAIN_CF.read_text(encoding="utf-8", errors="replace")
    merged = merge_main_cf(original, snippet)
    try:
        BACKUP_MAIN_CF.write_text(original, encoding="utf-8")
        _atomic_write(tmp_path, merged, mode=0o644)
        os.replace(tmp_path, SYSTEM_MAIN_CF)
    except PermissionError:
        # Helper copies tmp → main.cf as root.
        writable_tmp = POSTFIX_DIR / "main.cf.generated"
        _atomic_write(writable_tmp, merged, mode=0o644)


def postfix_check() -> tuple[bool, str]:
    if not shutil.which("postfix"):
        return False, "postfix binary not found"
    result = _run(["postfix", "check"])
    ok = result.returncode == 0
    output = (result.stdout + result.stderr).strip()
    return ok, output


def reload_postfix() -> tuple[bool, str]:
    if APPLY_HELPER.exists():
        result = _sudo([str(APPLY_HELPER)])
        if result.returncode != 0:
            return False, (result.stdout + result.stderr).strip()
        return True, (result.stdout or "postfix reloaded").strip()
    if not shutil.which("postfix"):
        return False, "postfix binary not found"
    check_ok, check_out = postfix_check()
    if not check_ok:
        if BACKUP_MAIN_CF.exists() and SYSTEM_MAIN_CF.exists():
            shutil.copy2(BACKUP_MAIN_CF, SYSTEM_MAIN_CF)
        return False, f"postfix check failed; configuration rolled back\n{check_out}"
    result = _sudo(["postfix", "reload"])
    if result.returncode != 0:
        return False, (result.stdout + result.stderr).strip()
    return True, "postfix reloaded"


def apply_and_reload(session: Session) -> dict:
    """Validate → write maps → merge main.cf → postfix check → reload → rollback on failure."""
    write_maps(session)
    try:
        apply_main_cf()
    except PermissionError:
        # Non-root API user: maps are in /etc/mailgate/postfix; helper compiles them.
        pass
    ok, message = reload_postfix()
    return {"ok": ok, "message": message}


def queue_json() -> list[dict]:
    if not shutil.which("postqueue"):
        return []
    result = _run(["postqueue", "-j"])
    if result.returncode != 0:
        return []
    items = []
    for line in result.stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        import json

        try:
            items.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return items


def queue_action(queue_id: str, action: str) -> tuple[bool, str]:
    if not queue_id.isalnum():
        return False, "Invalid queue id"
    if QUEUE_HELPER.exists():
        result = _sudo([str(QUEUE_HELPER), action, queue_id])
        return result.returncode == 0, (result.stdout + result.stderr).strip()
    if action == "retry":
        if not shutil.which("postqueue"):
            return False, "postqueue not found"
        result = _run(["postqueue", "-i", queue_id])
        return result.returncode == 0, (result.stdout + result.stderr).strip()
    if action == "delete":
        if not shutil.which("postsuper"):
            return False, "postsuper not found"
        result = _run(["postsuper", "-d", queue_id])
        return result.returncode == 0, (result.stdout + result.stderr).strip()
    return False, "Unknown action"


def inspect_queue(queue_id: str) -> tuple[bool, str]:
    if not queue_id.isalnum():
        return False, "Invalid queue id"
    if QUEUE_HELPER.exists():
        result = _sudo([str(QUEUE_HELPER), "inspect", queue_id])
        text = result.stdout
        if "\n\n" in text:
            headers, _body = text.split("\n\n", 1)
            text = headers + "\n\n[body omitted — MailGate does not display stored message bodies]"
        return result.returncode == 0, text or result.stderr
    if not shutil.which("postcat"):
        return False, "postcat not found"
    result = _run(["postcat", "-q", queue_id])
    # Strip message body by default — only return envelope/headers until blank line
    text = result.stdout
    if "\n\n" in text:
        headers, _body = text.split("\n\n", 1)
        text = headers + "\n\n[body omitted — MailGate does not display stored message bodies]"
    return result.returncode == 0, text or result.stderr
